reservation_project/accounts/urls.py
# accounts/urls.py
from django.urls import path
from .views import SignUpView
from .views import UserProfileView

app_name = 'accounts'

urlpatterns = [
    path('profile/', UserProfileView.as_view(), name='user_profile'),
    path('signup/', SignUpView.as_view(), name='signup'),
]

reservation_project/reservation/urls.py
# reservation/urls.py
from django.urls import path
from .views import home, MenuView, TableListView, AboutView, reserve_table, user_profile, select_table, register, logout_view, user_confirm
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', home, name='home'),
    # path('tables/', TableListView.as_view(), name='table_list'),
    path('user_confirm/', user_confirm, name='user_confirm'),
    path('about/', AboutView.as_view(), name='about'),
    path('menu/', MenuView.as_view(), name='menu'),
    path('reserve/', select_table, name='select_table'),
    path('reserve/<int:table_id>/', reserve_table, name='reserve_table'),
    path('profile/', user_profile, name='profile'),
    path('register/', register, name='register'),
    path('logout/', logout_view, name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html', success_url='/reservation/profile/'), name='login'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
]

reservation_project/reservation_project/urls.py
# reservation_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('reservation/', include('reservation.urls')),  # добавьте эту строку
]

reservation_project/reservation/models.py
# reservation/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# reservation/models.py

from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, timedelta

class Table(models.Model):
    number = models.IntegerField()
    seats = models.IntegerField()
    shape_choices = [('oval', 'Oval'), ('rectangle', 'Rectangle')]
    shape = models.CharField(max_length=10, choices=shape_choices)
    width = models.FloatField()
    length = models.FloatField()
    x_coordinate = models.FloatField()
    y_coordinate = models.FloatField()

    def is_reserved(self, date):
        reservations_for_date = Reservation.objects.filter(table=self, date=date)
        return reservations_for_date.exists()

    @staticmethod
    def get_available_tables(date):
        reserved_table_ids = Reservation.objects.filter(date=date).values_list('table_id', flat=True)
        return Table.objects.exclude(id__in=reserved_table_ids)

class Reservation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    table = models.ForeignKey(Table, on_delete=models.CASCADE)
    date = models.DateField()


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Dish(models.Model):
    name = models.CharField(max_length=255)
    weight = models.IntegerField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

reservation_project/reservation/forms.py
# reservation/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Reservation, Table
from datetime import date
from django.forms import ValidationError
from django.core.validators import MinValueValidator

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class ReservationForm(forms.Form):
    seats = forms.IntegerField(label='Number of seats')
    shape = forms.ChoiceField(
        label='Shape',
        choices=[('any', 'Any shape'), ('oval', 'Oval'), ('rectangle', 'Rectangle')],
        initial='any',
        widget=forms.Select(),
    )
    date = forms.DateField(label='Date', widget=forms.TextInput(attrs={'type': 'date'}))

class DateForm(forms.Form):
    date = forms.DateField(
        label='Choose a Date',
        widget=forms.TextInput(attrs={'type': 'date'}),
    )

    def clean_date(self):
        selected_date = self.cleaned_data['date']

        if selected_date < date.today():
            raise ValidationError('Please select a date from today onwards.')

        return selected_date

reservation_project/reservation/views.py
from django.contrib.auth.forms import UserCreationForm
from django.db.models import OuterRef, Subquery
from django.contrib.auth import login
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from .models import Table, Reservation
from django.contrib.auth import logout
from datetime import datetime
from .forms import ReservationForm
from django.views.generic import ListView
from .forms import DateForm
from django.views import View
from django.contrib import messages
from .models import Category, Dish
from django.http import HttpResponseBadRequest
from django.db.models import OuterRef, Subquery
from django.urls import reverse

class MenuView(View):
    template_name = 'reservation/menu.html'

    def get(self, request, *args, **kwargs):
        categories = Category.objects.all()
        dishes = Dish.objects.all()
        context = {'categories': categories, 'dishes': dishes}
        return render(request, self.template_name, context)

def home(request):
    return render(request, 'reservation/base.html')

class TableListView(View):
    template_name = 'reservation/table_list.html'

    def get(self, request, *args, **kwargs):
        form = DateForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = DateForm(request.POST)
        if form.is_valid():
            date = form.cleaned_data['date']

            available_tables = Table.objects.filter(
                last_reservation_date__lt=date
            )

            return render(request, self.template_name, {'tables': available_tables, 'date': date, 'form': form})

        return render(request, self.template_name, {'form': form})

class AboutView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'reservation/about.html')


def select_table(request):
    if request.method == 'POST':
        form = DateForm(request.POST)
        if form.is_valid():
            date = form.cleaned_data['date']
            available_tables = Table.get_available_tables(date)
            return render(request, 'reservation/table_list.html', {'tables': available_tables, 'date': date, 'form': form})
    else:
        form = DateForm()

    tables = Table.objects.all()
    return render(request, 'reservation/select_table.html', {'form': form, 'tables': tables})


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('table_list')
    else:
        form = UserCreationForm()
    return render(request, 'reservation/register.html', {'form': form})

@login_required
def reserve_table(request, table_id):
    table = get_object_or_404(Table, pk=table_id)
    date = request.POST.get('date')

    existing_reservation = Reservation.objects.filter(user=request.user, table=table, date=date).exists()
    if existing_reservation:
        error_message = "This table is already reserved."
        form = DateForm()
        tables = Table.objects.all()
        url = reverse('select_table')
        return render(request, 'reservation/select_table.html', {'reservation_error': error_message, 'redirect_url': url})

    if date:
        reservation = Reservation.objects.create(user=request.user, table=table, date=date)
        table.last_reservation_date = datetime.strptime(date, '%Y-%m-%d').date()
        table.save()
        return redirect('user_confirm')

    return redirect('select_table')


@login_required
def user_profile(request):
    reservations = Reservation.objects.filter(user=request.user)
    return render(request, 'reservation/user_profile.html', {'reservations': reservations})


def logout_view(request):
    logout(request)
    return redirect('home')

@login_required
def user_confirm(request):
    reservations = Reservation.objects.filter(user=request.user)
    return render(request, 'reservation/user_confirm.html', {'reservations': reservations})

reservation_project/reservation/templates/reservation/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1>About Us</h1>
    <div class="about-section">
        <img src="{% static 'reservation/images/3.jpg' %}" alt="Welcome Image" width="400" height="400" class="about__img">
        <p class="about__text">
            Welcome to Culinary Journey, where every meal is a celebration of flavors and traditions. 
            Established in [year], our restaurant has become a symbol of exquisite taste and exceptional service.
            At Culinary Journey, we take pride in sourcing the finest ingredients to craft dishes that not only delight the senses but also tell a story. 
            Our chefs blend creativity with tradition, offering you a unique and memorable dining experience.
        </p>
    </div>

    <div class="location-section">
        <h2>Where You Can Find Us:</h2>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d30161.35373531082!2d-74.02672152028799!3d40.71851043172058!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25a10ea3a7b65%3A0xfc9469329c17318b!2sSchilling%20Restaurant%20%26%20Bar!5e0!3m2!1suk!2sua!4v1702961346799!5m2!1suk!2sua" 
        width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>

{% endblock %}

reservation_project/reservation/templates/reservation/base.html
<!-- reservation/templates/base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    {% load static %}
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'reservation/css/styles.css' %}">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Reservation Site{% endblock %}</title>
</head>
<body>
    <header>
        <h1>{% block header %}My Reservation Site{% endblock %}</h1>
    </header>
    <nav>
        <ul>
            <li><a href="{% url 'home' %}">Main</a></li>
            <li><a href="{% url 'menu' %}">Menu</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'select_table' %}">Reserve a Table</a></li>
                <li><a href="{% url 'accounts:user_profile' %}">Profile</a></li>
                <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'login' %}">Login</a></li>
                <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
            {% endif %}
        </ul>
    </nav>
    <main>
        {% block content %}
        <h1>Welcome to Our Restaurant</h1>
            <section id="welcome" class="section">
                <div class="content">
                    <div class="text">
                        <h2>Welcome to Culinary Journey</h2>
                        <p>Indulge in a culinary journey where every dish is a masterpiece. Our chefs blend creativity and tradition to offer you a unique dining experience.</p>
                    </div>
                    <img src="{% static 'reservation/images/1.jpg' %}" alt="Welcome Image" width="400" height="400">
                </div>
            </section>

            <section id="about-us" class="section">
                <div class="content">
                    <div class="text">
                        <h2>Explore The Menu</h2>
                        <p>Explore the latest additions to our menu, crafted with passion and precision. Each dish is a fusion of flavors that promises to delight your taste buds.</p>
                        <!-- <p>Established in 2023, our restaurant has become a symbol of exquisite taste and exceptional service. We take pride in sourcing the finest ingredients and crafting dishes that delight the senses.</p> -->
                    </div>
                    <img src="{% static 'reservation/images/2.jpg' %}" alt="About Us Image" width="400" height="400">
                </div>
            </section>

            <section id="specialties" class="section">
                <div class="content">
                    <div class="text">
                        <h2>Our Specialties</h2>
                        <p>Explore our menu featuring a diverse range of culinary delights. From signature cocktails to chef's specials, each dish is a celebration of flavor and artistry.</p>
                    </div>
                    <img src="{% static 'reservation/images/5.jpg' %}" alt="Our Specialties Image" width="400" height="400">
                </div>
            </section>

            <section id="reservation" class="section">
                <div class="content">
                    <div class="text">
                        <h2>Reserve a Table</h2>
                        <p>Make your reservation now to savor an unforgettable dining experience. Whether it's a romantic dinner or a celebration with friends, we ensure every moment is special.</p>
                    </div>
                    <img src="{% static 'reservation/images/6.jpg' %}" alt="Reserve a Table Image" width="400" height="400">
                </div>
            </section>
        {% endblock %}
    </main>
</body>
</html>

reservation_project/reservation/templates/reservation/menu.html
{% extends 'base.html' %}

{% block content %}
    <h1>Menu:</h1>

    {% for category in categories %}
        <h2>{{ category.name }}</h2>
        <table>
            <colgroup>
                <col style="width: 40%;">
                <col style="width: 30%;">
                <col style="width: 30%;">
            </colgroup>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Weight</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
                {% for dish in dishes %}
                    {% if dish.category == category %}
                        <tr>
                            <td>{{ dish.name }}</td>
                            <td>{{ dish.weight }}g</td>
                            <td>${{ dish.price }}</td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>
    {% endfor %}
{% endblock %}

reservation_project/reservation/templates/reservation/reserve_table.html
<!-- reservation/templates/reservation/reserve_table.html -->
{% extends 'base.html' %}

{% block content %}
  <h2>Reserve Table {{ table.number }}</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Reserve</button>
  </form>
{% endblock %}

reservation_project/reservation/templates/reservation/select_table.html
{% extends 'base.html' %}

{% block content %}
  {% if reservation_error %}
    <h2 style="color: red;">{{ reservation_error }}</h2>
    <p style="color: red;">Choose different table.</p>
  {% endif %}
  <h2>Выберите дату</h2>
  <form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Show Tables</button>
  </form>
{% endblock %}

reservation_project/reservation/templates/reservation/table_list.html
<!-- reservation/templates/reservation/select_table.html -->
{% extends 'base.html' %}

{% block content %}
  <h2>Choose Reservation Date</h2>

  {% if form.errors %}
    <p style="color: red;">{{ form.errors }}</p>
  {% endif %}

  <form method="post" id="reservation-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Show Tables</button>
  </form>

  {% if date %}
    <h2>Available Tables on {{ date }}</h2>
    <div id="hall-layout">  
      {% for table in tables %}
        <form method="post" action="{% url 'reserve_table' table.id %}" class="reserve-form">
          {% csrf_token %}
          <input type="hidden" name="date" value="{{ date|date:'Y-m-d' }}">
          <input type="hidden" name="table_number" value="{{ table.number }}">
          <input type="hidden" name="table_seats" value="{{ table.seats }}">
          <button type="submit" class="reserve-button" {% if not table.is_reserved %}{% else %}disabled{% endif %}>
            {% if not table.is_reserved %}
              Reserve Table {{ table.number }} with {{ table.seats }} seats
            {% else %}
              This table is already reserved. Choose another one!
            {% endif %}
          </button>
        </form>
      {% endfor %}
    </div>
    {% if redirect_url %}
      <script>
        window.location.href = "{{ redirect_url }}";
      </script>
    {% endif %}
  {% endif %}
{% endblock %}

reservation_project/reservation/templates/reservation/user_confirm.html
<!-- reservation/templates/reservation/user_confirm.html -->
{% extends 'base.html' %}

{% block content %}
<h1>Reservation Successful</h1>
  <h2>Reservation History</h2>
  {% if reservations %}
    {% for reservation in reservations %}
      <div>
        <p>Date: {{ reservation.date }}</p>
        <p>Table Number: {{ reservation.table.number }}</p>
        <p>Seats: {{ reservation.table.seats }}</p>
      </div>
    {% endfor %}
  {% else %}
    <p>No active reservations.</p>
  {% endif %}
{% endblock %}

reservation_project/reservation/templates/reservation/user_profile.html
<!-- reservation/templates/reservation/user_profile.html -->
{% extends 'base.html' %}

{% block content %}
  <h2>Reservation History</h2>
  {% if reservations %}
    {% for reservation in reservations %}
      <div>
        <p>Date: {{ reservation.date }}</p>
        <p>Table Number: {{ reservation.table.number }}</p>
        <p>Seats: {{ reservation.table.seats }}</p>
      </div>
    {% endfor %}
  {% else %}
    <p>No reservation history.</p>
  {% endif %}
{% endblock %}